[project]
name = "sudan-cards"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "commentjson>=0.9.0",
    "dash>=3.0.2",
    "fire>=0.7.0",
    "pandas>=2.2.3",
]
